version = "1.0.0"

[server]
port = 8082

[provider]
# Default platform to use when none is specified
platform = "netease"


[log]
level = "debug"
file = "${HOME}/.miko/log.log"
format = "text"
stdout = true

[cookiecloud]
# official cookie cloud service
url = "https://ccc.ft07.com"
debug = false
timeout = 0
retry = 0

[database]
driver = "sqlite"
dsn = "${HOME}/.miko/miko.db"
