version = "1.0.0"

[server]
port = 8082

[registry]
# Default platform to use when none is specified
platform = "netease"


[log]
level = "debug"
file = "${HOME}/.miko/log.log"
format = "text"
stdout = true

[cookiecloud]
# url = "https://movie-pilot.org/cookiecloud"
url = "https://ccc.ft07.com"
debug = false
timeout = 0
retry = 0
sync_interval = "5m"
