[server]
port = 8082

[provider]
# Default platform to use when none is specified
platform = "netease"


[log]
level = "debug"
file = "${HOME}/.miko/log.log"
format = "text"
stdout = true

[cookiecloud]
# official cookie cloud service
url = "https://ccc.ft07.com"
debug = false
timeout = 0
retry = 0

[database]
driver = "sqlite"
dsn = "${HOME}/.miko/miko.db"

[subsonic]
folders = ["${HOME}/Music"]
dataDir = "${HOME}/.miko/data"
# default mode of scanning: "full" or "inc"
scanMode = "inc"
# how to index music files: by "tag" or "filepath"
browseMode = "tag"
ignoredArticles = "The El La Los Las Le Les"
