version = "1.0.0"

[server]
port = 8082

[registry]
default="netease"


[log]
level = "info"
file = "${HOME}/.miko/log.log"
format = "json"
stdout = true

[nmapi]
debug = false
timeout = 0
retry = 0

[nmapi.cookie]
filepath = "${HOME}/.miko/cookies.json"
interval = 0