version = "1.0.0"

[server]
port = 8082

[registry]
# Default platform to use when none is specified
platform = "netease"


[log]
level = "info"
file = "${HOME}/.miko/log.log"
format = "json"
stdout = true

[cookiecloud]
apiUrl = "http://192.168.50.2:3000/cookiecloud"
uuid = "uSfuMSt1RM6PdC8VX7J4Zy"
password = "vJEB7WLWDvCZ6auUVJxf5c"
syncInterval = "10m"
debug = false
timeout = 0
retry = 0

