[server]
port = 8082
# Secret used for encrypting passwords in the database. Better to set via environment variable MIKO_PASSWORD_SECRET
passwordSecret = "your-32-character-secret-here"
# Secret used for signing JWT tokens. Better to set via environment variable MIKO_JWT_SECRET
jwtSecret = "your-32-character-jwt-secret-here"

[provider]
# Default platform to use when none is specified
platform = "netease"


[log]
level = "debug"
file = "${HOME}/.miko/log.log"
format = "text"
stdout = true

[cookiecloud]
# official cookie cloud service
url = "https://ccc.ft07.com"
debug = false
timeout = 0
retry = 0

[database]
driver = "sqlite"
dsn = "${HOME}/.miko/miko.db"

[subsonic]
folders = ["${HOME}/Music"]
dataDir = "${HOME}/.miko/data"
# default mode of scanning: "full" or "inc"
scanMode = "inc"
# default mode of scraping: "full" or "inc"
scrapeMode = "inc"
ignoredArticles = "The El La Los Las Le Les"
